import type { FutsalMatch } from "./types";

export const SAMPLE_MATCHES: FutsalMatch[] = [
  {
    id: "fs-men-open-group-live",
    sport: "Futsal",
    discipline: "men-open",
    phase: "group",
    courtId: "court-2",
    court: "Court 2",
    sideA: { wilayahId: "kota-kinabalu" },
    sideB: { wilayahId: "tawau" },
    goalsA: 2,
    goalsB: 1,
    period: "h2",
    status: "live",
  },
  {
    id: "fs-women-group-draw",
    sport: "Futsal",
    discipline: "women",
    phase: "group",
    courtId: "court-1",
    court: "Court 1",
    sideA: { wilayahId: "sandakan" },
    sideB: { wilayahId: "lahad-datu" },
    goalsA: 2,
    goalsB: 2,
    period: "ft",
    status: "complete",
  },
  {
    id: "fs-men-veteran-ko-pens",
    sport: "Futsal",
    discipline: "men-veteran",
    phase: "knockout",
    courtId: "court-3",
    court: "Court 3",
    sideA: { wilayahId: "keningau" },
    sideB: { wilayahId: "kota-kinabalu" },
    goalsA: 3,
    goalsB: 3,
    period: "pen",
    penalties: { a: 4, b: 3 },
    status: "complete",
  },
];
