import type { BadmintonMatch } from "./types";

export const SAMPLE_MATCHES: BadmintonMatch[] = [
  {
    id: "bd-md-open-1",
    sport: "Badminton",
    discipline: "MD",
    category: "open",
    courtId: "court-3",
    court: "Court 3",
    sideA: { wilayahId: "kota-kinabalu", player1: "A. Lim", player2: "B. Chong" },
    sideB: { wilayahId: "sandakan", player1: "N. Tan", player2: "C. Ong" },
    games: [
      { a: 21, b: 19 },
      { a: 11, b: 8 },
    ],
    status: "live",
  },
  {
    id: "bd-md-vet-1",
    sport: "Badminton",
    discipline: "MD",
    category: "veteran",
    courtId: "court-1",
    court: "Court 1",
    sideA: { wilayahId: "tawau", player1: "Haziq Rahman", player2: "Rafi Noor" },
    sideB: { wilayahId: "lahad-datu", player1: "Farid Salleh", player2: "Azman Lee" },
    games: [
      { a: 21, b: 16 },
      { a: 19, b: 21 },
      { a: 21, b: 18 },
    ],
    status: "complete",
  },
  {
    id: "bd-wd-open-1",
    sport: "Badminton",
    discipline: "WD",
    category: "open",
    courtId: "court-2",
    court: "Court 2",
    sideA: { wilayahId: "keningau", player1: "Siti Aminah", player2: "Mei Tan" },
    sideB: { wilayahId: "kota-kinabalu", player1: "Aina Yusuf", player2: "Jo Park" },
    games: [{ a: 21, b: 20 }],
    status: "live",
  },
  {
    id: "bd-wd-vet-1",
    sport: "Badminton",
    discipline: "WD",
    category: "veteran",
    courtId: "court-4",
    court: "Court 4",
    sideA: { wilayahId: "sandakan", player1: "Nora Aziz", player2: "Kay Wong" },
    sideB: { wilayahId: "tawau", player1: "Lina Omar", player2: "Dee Chen" },
    games: [],
    status: "scheduled",
  },
  {
    id: "bd-xd-open-1",
    sport: "Badminton",
    discipline: "XD",
    category: "open",
    courtId: "court-1",
    court: "Court 1",
    sideA: { wilayahId: "lahad-datu", player1: "Irfan Malik", player2: "Hana Zulkifli" },
    sideB: { wilayahId: "keningau", player1: "Daniel Koh", player2: "Priya Nair" },
    games: [
      { a: 22, b: 20 },
      { a: 18, b: 21 },
      { a: 11, b: 8 },
    ],
    status: "live",
  },
  {
    id: "bd-xd-vet-1",
    sport: "Badminton",
    discipline: "XD",
    category: "veteran",
    courtId: "court-2",
    court: "Court 2",
    sideA: { wilayahId: "kota-kinabalu", player1: "Zulkifli Ahmad", player2: "Mariam Teo" },
    sideB: { wilayahId: "sandakan", player1: "Johan Ibrahim", player2: "Cathy Ng" },
    games: [
      { a: 21, b: 19 },
      { a: 21, b: 15 },
    ],
    status: "complete",
  },
];
