import type { DartMatch } from "./types";

export const SAMPLE_MATCHES: DartMatch[] = [
  {
    id: "dt-ms-live",
    sport: "Dart",
    discipline: "MS",
    boardId: "court-3",
    board: "Board 3",
    sideA: { wilayahId: "kota-kinabalu", players: ["Rafi"] },
    sideB: { wilayahId: "tawau", players: ["Haziq"] },
    legsA: 2,
    legsB: 2,
    remainingA: 241,
    remainingB: 316,
    currentLeg: 5,
    throwSide: "a",
    legHistory: [{ winner: "a" }, { winner: "b" }, { winner: "a" }, { winner: "b" }],
    status: "live",
  },
  {
    id: "dt-wp-final",
    sport: "Dart",
    discipline: "WP",
    boardId: "court-1",
    board: "Board 1",
    sideA: { wilayahId: "sandakan", players: ["Cathy Ng", "Mei Tan"] },
    sideB: { wilayahId: "lahad-datu", players: ["Hana Zulkifli", "Priya Nair"] },
    legsA: 4,
    legsB: 2,
    remainingA: 501,
    remainingB: 501,
    currentLeg: 7,
    throwSide: "a",
    legHistory: [
      { winner: "a" },
      { winner: "b" },
      { winner: "a" },
      { winner: "a" },
      { winner: "b" },
      { winner: "a" },
    ],
    status: "complete",
  },
];
